### ISSUE TITLE
Nextcloud Docker - Cadviewer drawings not loading / displayed

### ISSUE THREAD

**Issue by andrtau** [CADViewer/NextCloud#29]
Hello, 

im running Nextcloud 25.0.4 on Docker behind a  Traefik proxy. Regardin NC everything is working. 

I installed the CadViewer app by downloading the git and unziping it  in the apps\cadviewer directory. Setting permissions with the script worked. 
Running the Cadviewer Doctor i get all checkmarks but the .htaccess well configured stays red-crossed
![grafik](https://user-images.githubusercontent.com/128309486/226356380-d2b9ea19-1364-40cb-8ca8-b1ccf8500e1b.png)

The .htaccess seems to be correct:
 
![grafik](https://user-images.githubusercontent.com/128309486/226360118-0d293a9d-f526-4363-a322-e83ffdaaa397.png)

The Log seems ok, however the path look odd, with a // betwen converter and converters...

 NEW-FILE-CONVERSION-BEGIN   8.37.2  
 
Opening call-Api_Conversion_log.txt for new conversion: 
before _ isset()x2  
first in file   
$json_data:    
$json_request(conv): ,   
$temp_var is null:, this must be a post call, also:$jsonp_flag=, isset:1 request={"action":"svg_creation","converter":"AutoXchange AX2020","version":"V1.00","contentType":"file","customConversionEndpointExtension":false,"fileStamp":"2023-03-19T15:25:08+0000","contentLocation":"%2Fvar%2Fwww%2Fhtml%2Fdata%2FE15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F%2Ffiles%2FZeichnung1.dwg","contentFormat":"DWG","contentUsername":"","contentPassword":"","userLabel":"fromCADViewerJS","contentResponse":"stream","leaveStreamOnServer":0,"parameters":[{"paramName":"f","paramValue":"svg"},{"paramName":"strokea","paramValue":""},{"paramName":"last","paramValue":""},{"paramName":"extents","paramValue":""}]}<end request>$json_data isset, requestconverter:AutoXchange AX2020 
AGENT operating_system_detection():  $agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0  
AGENT PHP_OS : Linux
$contentlocation:  %2Fvar%2Fwww%2Fhtml%2Fdata%2FE15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F%2Ffiles%2FZeichnung1.dwg  
$contentlocation:  /var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg  
$max: 4  
param f : svg  
  $output_file_extension:svgz   $param_string:  -f="svgz" -strokea -last -extents  
  $svginputfile: 0  
We are setting $server_load:  1   /var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg 
after content location check $server_load:  0  , content-type: (file 
 location X004  contentlocation:/var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg 
X005 In action: contentype file: /var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg  
before download file  
 HELLO! /var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg  /var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg 
$fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg  
$fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg  
AA: before setting $fullPath:  $server_load 0   $contenttype file 
$fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg  
$max_conv: 5  
$engine_path: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_110  
new $add_xpath    
In loop to add xpath  
after first loop $command_line_parameter_xpath: 0  
after first loop $command_line_parameter_xpath: 0  converter AutoXchange AX2020   axconv 0 
adding xpath: $command_line: "/var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_110" -i="/var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg" -o="/var/www/html/apps/cadviewer/converter//converters/files/f111214438.svgz"  -f="svgz" -strokea -last -extents -fpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/fonts/"  -lpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/"  -xpath="/var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/"  XXXXXXX  
library path before new env: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux/  
this is the value we got setting the environment 1  
getenv after putenv: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux/   
before call to exec:  "/var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_110" -i="/var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg" -o="/var/www/html/apps/cadviewer/converter//converters/files/f111214438.svgz"  -f="svgz" -strokea -last -extents -fpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/fonts/"  -lpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/"  -xpath="/var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/"     
before call to exec, engine_path:  /var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_110    
current script owner: root    
AGENT operating_system_detection():  $agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0  
AGENT PHP_OS : Linux
operating_system_detection(): Linux    
BEFORE CACHED CONVERSION t: c: 11  0    

 CACHED CONVERSION IMPLEMENT  {\"fullfilepath\": \"full file path\",\"filename\": \"filename\",\"filecreatestamp\": \"date1\",\"filechangestamp\": \"2023-01-31T08:30:25.597Z\",\"cachedfiles\": [{ \"fileName\": \"F1.svgz\", \"filecreatestamp\": \"datef1\", \"parameters\": [{\"paramName\": \"f\", \"paramValue\": \"svg\"}]}]} 

 FILENAME:/var/www/html/apps/cadviewer/converter//converters/files/Zeichnung1.dwg.json 

file exists: /var/www/html/apps/cadviewer/converter//converters/files/Zeichnung1.dwg.json 1XXX

cashedfile likely  in array good XXX

number of conversion: 1XXX

before file: 0  f1195678864.svgzXXX

file: 0  f1195678864.svgzXXX

param match: 0  f svgz XXX

param match: 1  strokea  XXX

param match: 2  last  XXX

param match: 3  extents  XXX

 timeStamp= 2023-03-19T15:25:08+0000  jarray['filecreatestamp']= 2023-03-19T18:21:12+00:00

 timeStamp= 1679239508  jarray['filecreatestamp']= 1679250072

temp_file_name= f1195678864  XXX output_file_extension= svgz

Do nothing! we are just loading in the old temp svgz....exec return1 check  0   
unlink2  /var/www/html/apps/cadviewer/converter//converters/files/f111214438.dwg   
Q1 contentresponse  stream   
Q2:svg_creation   
Q4: $general_response{"completedAction":"svg_creation","errorCode":"E0","converter":"AutoXchange AX2020","version":"V1.00","userLabel":"fromCADViewerJS","contentLocation":"/var/www/html/data/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F/files/Zeichnung1.dwg","contentResponse":"stream","contentStreamData":"http://nextcloud.domain.de/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f1195678864&Type=svgz"}   
Q5: 0  1  $json_response"{\"completedAction\":\"svg_creation\",\"errorCode\":\"E0\",\"converter\":\"AutoXchange AX2020\",\"version\":\"V1.00\",\"userLabel\":\"fromCADViewerJS\",\"contentLocation\":\"\/var\/www\/html\/data\/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F\/files\/Zeichnung1.dwg\",\"contentResponse\":\"stream\",\"contentStreamData\":\"http:\/\/nextcloud.domain.de\/apps\/cadviewer\/converter\/\/php\/\/getFile_09.php?remainOnServer=1&fileTag=f1195678864&Type=svgz\"}"   
$json_response = "{\"completedAction\":\"svg_creation\",\"errorCode\":\"E0\",\"converter\":\"AutoXchange AX2020\",\"version\":\"V1.00\",\"userLabel\":\"fromCADViewerJS\",\"contentLocation\":\"\/var\/www\/html\/data\/E15E3EA9-BB09-4C91-9F6F-E1C6801B5E2F\/files\/Zeichnung1.dwg\",\"contentResponse\":\"stream\",\"contentStreamData\":\"http:\/\/nextcloud.domain.de\/apps\/cadviewer\/converter\/\/php\/\/getFile_09.php?remainOnServer=1&fileTag=f1195678864&Type=svgz\"}"  
$post_request_flag=1 $json_response only  
LAST BEFORE CALLBACK   `

Inspecting the console in firefox the paths even get more strange:
![grafik](https://user-images.githubusercontent.com/128309486/226358306-fdaae4f0-7782-49d2-8efe-c1dbdbd309b8.png)

Traefik labels are: 

"traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.domain.de`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.domain.de`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nc-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nc-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nc-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nc-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.nextcloud-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

Not sure it it is related to https://github.com/nextcloud/docker/issues/1366 or traefik or someting else, help welcome

**Comment by CADViewer** [comment]
@andrtau , I think the .htaccess check probably wants the RewriteRule just before the RewriteCond, so that's something we need to check.  It appears that the conversion is triggered, but it says that it has a cached file that it is attempting to load. 

1) In the admin tool, clear the cache, there is a button for that.

2) In your browser, enable the developer console,  Ctrl+Shift+I, to monitor front-end traffic.

3) Run again, and send us the traces

Thanks!

**Comment by andrtau** [comment]
Moving the Rule directly above the condition did not make andy diffrence. Still the red X at Cadviewer Doctor.

Here comes the trace, still with paths that dont exist (files/assets/cadviewer/)

GEThttps://nextcloud.domain.de/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0
[HTTP/2 404 Not Found 32ms]

Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    h focus-trap.esm.js:358
    activate focus-trap.esm.js:635
    t NcModal.js:2
    d NcModal.js:2
    y NcModal.js:2
    b NcModal.js:2
    A NcModal.js:2
    r NcModal.js:2
    promise callback*A NcModal.js:2
    r NcModal.js:2
    useFocusTrap NcModal.js:2
    useFocusTrap NcModal.js:2
    useFocusTrap NcModal.js:2
    mounted NcModal.js:2
    VueJS 19
    viewCadFileActionHandler CADViewerCanvas.vue:922
    action merged-index.js:3067
    _onClickFile merged-index.js:5042
    Underscore 3
    jQuery 10
    initialize merged-index.js:4515
    FileList merged-index.js:4163
    initialize merged-index.js:91
    <anonymous> merged-index.js:442
    Underscore 5
    <anonymous> merged-index.js:441
    EventListener.handleEvent* merged-index.js:438
focus-trap.esm.js:358:22
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://nextcloud.domain.de/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0
GEThttps://nextcloud.domain.de/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0
[HTTP/2 404 Not Found 33ms]

XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: https://nextcloud.domain.de/apps/files/?dir=/&fileid=537293
Zeile Nr. 1, Spalte 1: SessionList.vue:2
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://nextcloud.domain.de/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0
GEThttps://nextcloud.domain.de/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0
[HTTP/2 404 Not Found 38ms]

XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: https://nextcloud.domain.de/apps/files/?dir=/&fileid=537293
Zeile Nr. 1, Spalte 1: SessionList.vue:2
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: https://nextcloud.domain.de/apps/files/?dir=/&fileid=537293
Zeile Nr. 1, Spalte 1: SessionList.vue:2
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://nextcloud.domain.de/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0
Laden von gemischten aktiven Inhalten "http://nextcloud.domain.de/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f1524388761&Type=svgz" wurde blockiert. cadviewer_8.52.4.min.js:2:2716803

**Comment by CADViewer** [comment]
@andrtau , thanks, it can possibly be your traffic proxy,which we then have to emulate,  The acual loading of the converted drawing is happening in  "http://nextcloud.domain.de/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f1524388761&Type=svgz , which is blocked for you.    Strangely enough, this load request is out of context.  The server side lists(?) that a conversion request was sent and received,  but your Chrome trace above does not display it above.   

Do you in your browser trace, see something like this (different url + filename for you of course)?
 
CADViewer - v8.54.1 , php, url:http://localhost/nextcloud/apps/cadviewer/converter/php/call-Api_Conversion.php request: {"action":"svg_creation","converter":"AutoXchange AX2020","version":"V1.00","contentType":"file","customConversionEndpointExtension":false,"fileStamp":"2023-01-02T15:42:18+0000","contentLocation":"%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2Fdata%2Fcadviewer_admin%2Ffiles%2FDrawings%20-%20CADViewer%20tests%2F046-test-%C3%A4%C3%B6%C3%BC%C3%9F-.dgn","contentFormat":"DGN","contentUsername":"","contentPassword":"","userLabel":"fromCADViewerJS","contentResponse":"stream","leaveStreamOnServer":0,"parameters":[{"paramName":"f","paramValue":"svg"},{"paramName":"strokea","paramValue":""},{"paramName":"last","paramValue":""},{"paramName":"extents","paramValue":""}]}

This request, is what trigger the conversion on the back-end.

**Comment by andrtau** [comment]
Did a fresh "install" now running nc 26.
After installing the Ap via Appstore it was stored in custom_apps, many links didnt work, the gui was unusable. Moving it to apps solved that issue.

Still the drwaings dont show. Opening a dwg in chrome it seems that some pathes arent right:
```

/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0 net::ERR_ABORTED 404
7fb327672c3942593137.png:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/7fb327672c3942593137.png 404
fc5235bced448936ae78.png:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/fc5235bced448936ae78.png 404
83c974c262fcbcd8aed0.png:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/83c974c262fcbcd8aed0.png 404
46da1f02756f28610528.png:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/46da1f02756f28610528.png 404
cadviewer_8.54.1.min.js:2 Refused to connect to 'http://nextcloud.tld.biz/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f1450707950&Type=svgz' because it violates the following Content Security Policy directive: "connect-src 'self' blob: stun.nextcloud.com:443".

e.ajax @ cadviewer_8.54.1.min.js:2
e.load @ cadviewer_8.54.1.min.js:2
Tg @ cadviewer_8.54.1.min.js:2
(anonymous) @ cadviewer_8.54.1.min.js:2
Qh @ cadviewer_8.54.1.min.js:2
pg @ cadviewer_8.54.1.min.js:2
success @ cadviewer_8.54.1.min.js:2
l @ cadviewer_8.54.1.min.js:2 
fireWith @ cadviewer_8.54.1.min.js:2
k @ cadviewer_8.54.1.min.js:2
(anonymous) @ cadviewer_8.54.1.min.js:2
load (async)
send @ cadviewer_8.54.1.min.js:2
ajax @ cadviewer_8.54.1.min.js:2
ag @ cadviewer_8.54.1.min.js:2
rU @ cadviewer_8.54.1.min.js:2
sU @ cadviewer_8.54.1.min.js:2
og @ cadviewer_8.54.1.min.js:2
(anonymous) @ cadviewer_8.54.1.min.js:2
Qh @ cadviewer_8.54.1.min.js:2
Wh @ cadviewer_8.54.1.min.js:2
initCadviewer @ CADViewerCanvas.vue:735
(anonymous) @ CADViewerCanvas.vue:946
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:42
r @ CADViewerCanvas.vue:52
(anonymous) @ CADViewerCanvas.vue:98
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:954
l @ jquery.js:3500
fireWith @ jquery.js:3630
w @ jquery.js:9796
(anonymous) @ jquery.js:10057
/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0 net::ERR_ABORTED 404
/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0:1          GET https://nextcloud.tld.biz/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0 net::ERR_ABORTED 404
```
this one seems to me the main problem: 

`cadviewer_8.54.1.min.js:2 Refused to connect to 'http://nextcloud.tld.biz/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f1450707950&Type=svgz' because it violates the following Content Security Policy directive: "connect-src 'self' blob: stun.nextcloud.com:443".`

**Comment by CADViewer** [comment]
Hello @andrtau ,   looking at your trace above, then both the  nextcloud.  concatenation issue in the firefox console path, has been solved in v8.59.19, so please update and check.  -Also, in v8.59.19, there is a general fix for installations with CSP applied.-

**Comment by andrtau** [comment]
> Hello @andrtau , looking at your trace above, then both the nextcloud. concatenation issue in the firefox console path, has been solved in v8.59.19, so please update and check. -Also, in v8.59.19, there is a general fix for installations with CSP applied.-

Hi @CADViewer  , tahnks for the heads up. Updated to the latest version. Still cant open files. Cadviewer Doctor isnt satisfied with the permissions... See Screenshots attached. 
![grafik](https://user-images.githubusercontent.com/128309486/234225293-41ee2d5e-e4f7-4c15-abbe-a6968ad210f5.png)

**Comment by andrtau** [comment]
Now all blue checks in Cadviewer Doctor, still no Draing displayed:

```
NEW-FILE-CONVERSION-BEGIN   8.37.2  
 
Opening call-Api_Conversion_log.txt for new conversion: 
before _ isset()x2  
first in file   
$json_data:    
$json_request(conv): ,   
$temp_var is null:, this must be a post call, also:$jsonp_flag=, isset:1 request={"action":"svg_creation","originatinglocation":"http://localhost:8081/apps/files/?dir=/&fileid=2","converter":"AutoXchange AX2020","version":"V1.00","contentType":"file","customConversionEndpointExtension":false,"fileStamp":"2021-12-12T07:55:31+0000","contentLocation":"%2Fvar%2Fwww%2Fhtml%2Fdata%2Fnextcloud%2Ffiles%2F1st%20floor%20lighting.dwg","contentFormat":"DWG","contentUsername":"","contentPassword":"","userLabel":"fromCADViewerJS","contentResponse":"stream","leaveStreamOnServer":0,"parameters":[{"paramName":"f","paramValue":"svg"},{"paramName":"model","paramValue":""},{"paramName":"extents","paramValue":""},{"paramName":"t","paramValue":"svg"}]}<end request>$json_data isset, requestconverter:AutoXchange AX2020 
AGENT operating_system_detection():  $agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0  
AGENT PHP_OS : Linux
$contentlocation:  %2Fvar%2Fwww%2Fhtml%2Fdata%2Fnextcloud%2Ffiles%2F1st%20floor%20lighting.dwg  
$contentlocation:  /var/www/html/data/nextcloud/files/1st%20floor%20lighting.dwg  
$max: 4  
param f : svg  
param t : svg  
  $output_file_extension:svgz   $param_string:  -f="svgz" -model -extents -t="svg"  
  $svginputfile: 0  
We are setting $server_load:  1   /var/www/html/data/nextcloud/files/1st floor lighting.dwg 
after content location check $server_load:  0  , content-type: (file 
 location X004  contentlocation:/var/www/html/data/nextcloud/files/1st floor lighting.dwg 
X005 In action: contentype file: /var/www/html/data/nextcloud/files/1st floor lighting.dwg  
before download file  
 HELLO! /var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg  /var/www/html/data/nextcloud/files/1st floor lighting.dwg 
urldecode: /var/www/html/data/nextcloud/files/1st floor lighting.dwg 
 $fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg  
$fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg  
AA: before setting $fullPath:  $server_load 0   $contenttype file 
$fullPath: /var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg  
$max_conv: 5  
$engine_path: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_113b  
new $add_xpath    
In loop to add xpath  
after first loop $command_line_parameter_xpath: 0  
after first loop $command_line_parameter_xpath: 0  converter AutoXchange AX2020   axconv 0 
adding xpath: $command_line: "/var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_113b" -i="/var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg" -o="/var/www/html/apps/cadviewer/converter//converters/files/f670481786.svgz"  -f="svgz" -model -extents -t="svg" -fpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/fonts/"  -lpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/"  -xpath="/var/www/html/data/nextcloud/files/"  XXXXXXX  
library path before new env: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux/  
this is the value we got setting the environment 1  
getenv after putenv: /var/www/html/apps/cadviewer/converter//converters/ax2024/linux/   
before call to exec:  "/var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_113b" -i="/var/www/html/apps/cadviewer/converter//converters/files/f670481786.dwg" -o="/var/www/html/apps/cadviewer/converter//converters/files/f670481786.svgz"  -f="svgz" -model -extents -t="svg" -fpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/fonts/"  -lpath="/var/www/html/apps/cadviewer/converter//converters/ax2024/linux/"  -xpath="/var/www/html/data/nextcloud/files/"     
before call to exec, engine_path:  /var/www/html/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_113b    
current script owner: www-data    
AGENT operating_system_detection():  $agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0  
AGENT PHP_OS : Linux
operating_system_detection(): Linux    
BEFORE CACHED CONVERSION t: c: 11  0    

 CACHED CONVERSION IMPLEMENT  {\"filename\": \"filename\",\"filecreatestamp\": \"date1\",\"filechangestamp\": \"2023-01-31T08:30:25.597Z\",\"cachedfiles\": [{ \"fullfilepath\": \"full file path\", \"fileName\": \"F1.svgz\", \"filecreatestamp\": \"datef1\", \"parameters\": [{\"paramName\": \"f\", \"paramValue\": \"svg\"}]}]} 

 FILENAME:/var/www/html/apps/cadviewer/converter//converters/files/1st floor lighting.dwg.json 

file exists: /var/www/html/apps/cadviewer/converter//converters/files/1st floor lighting.dwg.json XXX

CANNOT OPEN FILE, NEED TO BUILD JSON STRUCTURE  XXX 

parameters size: 4  XXX jarray new file: {"filename":"1st floor lighting.dwg","filecreatestamp":"2023-05-11T09:03:01+00:00","cachedfiles":[{"fullfilepath":"\/var\/www\/html\/data\/nextcloud\/files","fileName":"f670481786.svgz","filecreatestamp":"2023-05-11T09:03:01+00:00","parameters":[{"paramName":"f","paramValue":"svgz"},{"paramName":"model","paramValue":""},{"paramName":"extents","paramValue":""},{"paramName":"t","paramValue":"svg"}]}]} XXX 

 single entry fullfilepath in cache: /var/www/html/data/nextcloud/files 

 exec return1  0   
exec return1 check  0   
Q1 contentresponse  stream   
Q2:svg_creation   
Q4: $general_response{"completedAction":"svg_creation","errorCode":"E0","converter":"AutoXchange AX2020","version":"V1.00","userLabel":"fromCADViewerJS","contentLocation":"/var/www/html/data/nextcloud/files/1st floor lighting.dwg","contentResponse":"stream","contentStreamData":"http://localhost:8081/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f670481786&Type=svgz"}   
Q5: 0  1  $json_response"{\"completedAction\":\"svg_creation\",\"errorCode\":\"E0\",\"converter\":\"AutoXchange AX2020\",\"version\":\"V1.00\",\"userLabel\":\"fromCADViewerJS\",\"contentLocation\":\"\/var\/www\/html\/data\/nextcloud\/files\/1st floor lighting.dwg\",\"contentResponse\":\"stream\",\"contentStreamData\":\"http:\/\/localhost:8081\/apps\/cadviewer\/converter\/\/php\/\/getFile_09.php?remainOnServer=1&fileTag=f670481786&Type=svgz\"}"   
$json_response = "{\"completedAction\":\"svg_creation\",\"errorCode\":\"E0\",\"converter\":\"AutoXchange AX2020\",\"version\":\"V1.00\",\"userLabel\":\"fromCADViewerJS\",\"contentLocation\":\"\/var\/www\/html\/data\/nextcloud\/files\/1st floor lighting.dwg\",\"contentResponse\":\"stream\",\"contentStreamData\":\"http:\/\/localhost:8081\/apps\/cadviewer\/converter\/\/php\/\/getFile_09.php?remainOnServer=1&fileTag=f670481786&Type=svgz\"}"  
$post_request_flag=1 $json_response only  
LAST BEFORE CALLBACK 
```  
 
After inspecting the browser debug it seems it is blocked by Mixed content policy of Firefox caus [cadviewer_8.54.1.min.js:2:2716803](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.54.1.min.js) contains some:

```
https://nextcloud.tld.biz/apps/files/?dir=/&fileid=515' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://nextcloud.tld.biz/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f822127228&Type=svgz'. This request has been blocked; the content must be served over HTTPS.
e.ajax @ cadviewer_8.54.1.min.js
```

Any suggestions?

**Comment by CADViewer** [comment]
Hi @andrtau , can you please send the full content of the browser inspector, Ctrl+Shift+I, the Console Info part?   yes, It seems like the mixed content issue prevents loading. Thanks!

**Comment by RJPvT** [comment]
follow, also having this problem

**Comment by RJPvT** [comment]
@CADViewer hereby my console logs :
Object { context: {…}, tr: {…}, filename: "2236E15-a.dwg" }
[CADViewerCanvas.vue:952](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    h focus-trap.esm.js:358
    activate focus-trap.esm.js:635
    t NcModal.js:2
    d NcModal.js:2
    y NcModal.js:2
    b NcModal.js:2
    A NcModal.js:2
    r NcModal.js:2
    promise callback*A NcModal.js:2
    r NcModal.js:2
    useFocusTrap NcModal.js:2
    useFocusTrap NcModal.js:2
    useFocusTrap NcModal.js:2
    mounted NcModal.js:2
    VueJS 19
    viewCadFileActionHandler CADViewerCanvas.vue:960
    action merged-index.js:3046
    _onClickFile merged-index.js:5023
    Underscore 3
    jQuery 10
    initialize merged-index.js:4499
    FileList merged-index.js:4142
    initialize merged-index.js:82
    <anonymous> merged-index.js:406
    Underscore 5
    <anonymous> merged-index.js:405
    EventListener.handleEvent* merged-index.js:402
[focus-trap.esm.js:358:22](webpack:///cadviewer/node_modules/focus-trap/dist/focus-trap.esm.js)
Object { content_dir: "/var/www/nextcloud/data/ncadmin/files" }
[CADViewerCanvas.vue:968](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
Object { axparameters: {…} }
[CADViewerCanvas.vue:997](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
mounted [CADViewerCanvas.vue:462](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
ServerBackEndUrl, ServerLocation, ServerUrl, FileName declared: [CADViewerCanvas.vue:490](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
cvjs_setCADViewerInterfaceVersion   - version:CADViewer - v8.80.6 [cadviewer_8.80.6.min.js:2:1715217](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
The language is (imported from NextCloud):nl [CADViewerCanvas.vue:602](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
The language: languages[thelanguage]:undefined [CADViewerCanvas.vue:625](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
cvjs_loadCADViewerLanguage -version:CADViewer - v8.80.6 [cadviewer_8.80.6.min.js:2:1711304](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_setTopMenuXML -version:CADViewer - v8.80.6  cadviewer_redlines_fileload_nextcloud_04.xml [cadviewer_8.80.6.min.js:2:1714239](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_InitCADViewer_highLight_popUp_app -version:CADViewer - v8.80.6 [cadviewer_8.80.6.min.js:2:1666221](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_findMaxRedlineStickyNote: max=0 [cadviewer_8.80.6.min.js:2:1681347](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
exception: cvjsspace_clearSpaceObjects [cadviewer_8.80.6.min.js:2:2723433](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0
[HTTP/2 404 Not Found 62ms]

XML-parsefout: syntaxisfout
Locatie: https://filecloud.jvtbv.nl/apps/files/?dir=/&fileid=2
Regelnummer 1, kolom 1: [ActivityTab.vue:2](webpack://./src/views/ActivityTab.vue)
Languages: 9 [cadviewer_8.80.6.min.js:2:1533881](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/7fb327672c3942593137.png
[HTTP/2 404 Not Found 60ms]

cvjs_InitializeModals_helper07_allMethodsAfterLanguageLoad: cvjs_loadTopIconMenuVisible[cvjs_interfaceCounterIndex(f_div)floorPlan_svg  0 true [cadviewer_8.80.6.min.js:2:1534434](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_regenerateTopIconMenuXMLtrue [cadviewer_8.80.6.min.js:2:1508247](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
LOAD EXERNAL MENU: [cadviewer_8.80.6.min.js:2:1508592](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
CADViewer - v8.80.6 nodejs/php before load:post js_data:{"file":"/var/www/nextcloud/apps/cadviewer/converter//app/cv/cv-pro/menu_config/cadviewer_redlines_fileload_nextcloud_04.xml","listtype":"","loadtype":""} [cadviewer_8.80.6.min.js:2:1510264](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Synchrone XMLHttpRequest op de hoofdthread wordt niet meer ondersteund vanwege de nadelige effecten op de eindgebruikerservaring. Zie http://xhr.spec.whatwg.org/ voor meer informatie [cadviewer_8.80.6.min.js:2:901555](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://filecloud.jvtbv.nl/apps/files/assets/cadviewer/20fd1704ea223900efa9.woff2?v=4.7.0
Deze pagina gebruikt de niet-standaard property ‘zoom’. Overweeg het gebruik van calc() in de relevante propertywaarden of gebruik ‘transform’ samen met ‘transform-origin: 0 0’. [files](https://filecloud.jvtbv.nl/apps/files/?dir=/&fileid=2)
XHRPOSThttps://filecloud.jvtbv.nl/apps/cadviewer/converter/php/load-file.php
[HTTP/2 404 Not Found 60ms]

GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0
[HTTP/2 404 Not Found 42ms]

Error : <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="nl" data-locale="nl" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			fileCloud		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/apps/theming/favicon?v=cb4e5208">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=cb4e5208">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=cb4e5208">
		<link rel="stylesheet" href="/core/css/server.css?v=09eaa108-32">
<link rel="stylesheet" href="/apps/extract/css/style.css?v=7178aad2-32">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=34e90de1-32">
<link rel="stylesheet" href="/core/css/guest.css?v=09eaa108-32">
		<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/dist/core-common.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/dist/core-main.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/core/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/dist/core-files_fileinfo.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/dist/core-files_client.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/js/core/merged-template-prepend.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/apps/extract/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/apps/extract/js/extraction.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/apps/files_sharing/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="RDFoNFk5UHBzNmgzN2ZLTGVGUHFkTGF5L0twcVZmeTVUbUFJUlRhNFBrcz06YmowM0ZiaWh3KzRmZzVua1B5YVRUSWJLMDRVbklMM2FOaVpmZlhIUmFCND0=" defer src="/dist/files_sharing-main.js?v=09eaa108-32"></script>
			</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Deze applicatie heeft JavaScript nodig. <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">Activeer JavaScript</a> en ververs deze pagina.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-core-versionHash" value="IjA5ZWFhMTA4Ig==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						fileCloud					</h1>
					<div class="guest-box">
	<h2>Fout</h2>
	<ul>
			<li>
			<p>404</p>
							<p class='hint'>Deze pagina kon niet gevonden worden op de server</p>
					</li>
		</ul>
</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://filecloud.jvtbv.nl/" target="_blank" rel="noreferrer noopener" class="entity-name">fileCloud</a> – J. van Toorenburg BV remote file access			</p>
		</footer>
	</body>
</html>
[cadviewer_8.80.6.min.js:2:1511279](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/fc5235bced448936ae78.png
[HTTP/2 404 Not Found 55ms]

GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/db73661e15731459fc8b.png
[HTTP/2 404 Not Found 65ms]

GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/46da1f02756f28610528.png
[HTTP/2 404 Not Found 54ms]

Installation using class name is DEPRECATED. Use data-jscolor="" attribute instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:1153](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Option 'insetColor' is DEPRECATED, using 'controlBorderColor' instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:20167](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Option 'closable' is DEPRECATED, using 'closeButton' instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:20167](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Installation using class name is DEPRECATED. Use data-jscolor="" attribute instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:1153](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Option 'insetColor' is DEPRECATED, using 'controlBorderColor' instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:20167](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Option 'closable' is DEPRECATED, using 'closeButton' instead. See https://jscolor.com/docs/ [cadviewer_8.80.6.min.js:2:20167](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_setLicenseKeyDirect   - version:CADViewer - v8.80.6 [cadviewer_8.80.6.min.js:2:2341547](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
ISOtimeStamp=2023-08-04T12:38:20+0000 [CADViewerCanvas.vue:767](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
CADViewer - v8.80.6 (php,vuejs) Loading: 2236E15-a.dwg [cadviewer_8.80.6.min.js:2:1674949](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
CADViewer - v8.80.6 cvjs_FileNameNoExtension=, SVGloadFlag=false) [cadviewer_8.80.6.min.js:2:1675543](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
svgFileFromServer=false cvjs_FileNameNoExtension: 2236E15-a fileExtension=dwg fileExtensionLower:dwg [cadviewer_8.80.6.min.js:2:1676573](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
cvjs_fileExtensionDWG [cadviewer_8.80.6.min.js:2:1679268](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
Init load: conversion parameter: f svg [cadviewer_8.80.6.min.js:2:1686399](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
CADViewer - v8.80.6 , php, date:Thu Aug 17 2023 23:04:49 GMT+0200 (Midden-Europese zomertijd), url:https://filecloud.jvtbv.nl/apps/cadviewer/converter/php/call-Api_Conversion.php request: {"action":"svg_creation","originatinglocation":"https://filecloud.jvtbv.nl/apps/files/?dir=/&fileid=2","converter":"AutoXchange AX2020","version":"V1.00","contentType":"file","customConversionEndpointExtension":false,"fileStamp":"2023-08-04T12:38:20+0000","contentLocation":"%2Fvar%2Fwww%2Fnextcloud%2Fdata%2Fncadmin%2Ffiles%2F2236E15-a.dwg","contentFormat":"DWG","contentUsername":"","contentPassword":"","userLabel":"fromCADViewerJS","contentResponse":"stream","leaveStreamOnServer":0,"parameters":[{"paramName":"f","paramValue":"svg"},{"paramName":"model","paramValue":""},{"paramName":"extents","paramValue":""}]} [cadviewer_8.80.6.min.js:2:1690450](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
XHRPOSThttps://filecloud.jvtbv.nl/apps/cadviewer/converter/php/call-Api_Conversion.php
[HTTP/2 404 Not Found 69ms]

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://filecloud.jvtbv.nl/apps/files/assets/cadviewer/f691f37e57f04c152e23.woff?v=4.7.0
GEThttps://filecloud.jvtbv.nl/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0
[HTTP/2 404 Not Found 36ms]

jsonp getEngines error=<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="nl" data-locale="nl" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			fileCloud		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/apps/theming/favicon?v=cb4e5208">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=cb4e5208">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=cb4e5208">
		<link rel="stylesheet" href="/core/css/server.css?v=09eaa108-32">
<link rel="stylesheet" href="/apps/extract/css/style.css?v=7178aad2-32">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=34e90de1-32">
<link rel="stylesheet" href="/core/css/guest.css?v=09eaa108-32">
		<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/dist/core-common.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/dist/core-main.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/core/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/dist/core-files_fileinfo.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/dist/core-files_client.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/js/core/merged-template-prepend.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/apps/extract/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/apps/extract/js/extraction.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/apps/files_sharing/l10n/nl.js?v=09eaa108-32"></script>
<script nonce="VFZVcWMwd1NCV1BLbnE5dUVxamlwRUJ0cVUrMEdPSkcyRElpaTdQVzVTWT06TERCbEJTZGFkU1dpOE1RQlZkMmJuSEFWaG1ENWJhTWxvSFIxcy9TL3MzTT0=" defer src="/dist/files_sharing-main.js?v=09eaa108-32"></script>
			</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Deze applicatie heeft JavaScript nodig. <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">Activeer JavaScript</a> en ververs deze pagina.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-core-versionHash" value="IjA5ZWFhMTA4Ig==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						fileCloud					</h1>
					<div class="guest-box">
	<h2>Fout</h2>
	<ul>
			<li>
			<p>404</p>
							<p class='hint'>Deze pagina kon niet gevonden worden op de server</p>
					</li>
		</ul>
</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://filecloud.jvtbv.nl/" target="_blank" rel="noreferrer noopener" class="entity-name">fileCloud</a> – J. van Toorenburg BV remote file access			</p>
		</footer>
	</body>
</html>
 status=error error=Not Found [cadviewer_8.80.6.min.js:2:1690750](webpack:///cadviewer/node_modules/cadviewer/dist/cadviewer_8.80.6.min.js)
RESIZE - cvjs_resizeWindow_position [CADViewerCanvas.vue:775](webpack:///cadviewer/src/components/CADViewerCanvas.vue)
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://filecloud.jvtbv.nl/apps/files/assets/cadviewer/1e59d2330b4c6deb84b3.ttf?v=4.7.0
downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:5) source: (end of source list)

​

**Comment by CADViewer** [comment]
@RJPvT , we think you have a proxy server where the front-end is https and the back-end is http.   Can you please tell us which proxy server you are using?     Then we can make the appropriate tests. Thanks!

**Comment by RJPvT** [comment]
Hi! 

We only have nginx running in between, standard nextcloud setup. Anything i can do to check ?

**Comment by RJPvT** [comment]
> Hi!
> 
> We only have nginx running in between, standard nextcloud setup. Anything i can do to check ?

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

**Comment by CADViewer** [comment]
Hello @RJPvT , since there is several updates since then, we are closing this issue. If you can replicate with a newer version of CADViewer and Nextcloud, please let us know!
