### ISSUE TITLE
There are some errors and can not open any dwg

### ISSUE THREAD

**Issue by bluestar800** [CADViewer/NextCloud#66]
nextcloud：27.0.2
OS：OMV 6.0（debian 11）
nextcloud is installed in host
The nextcloud root folder is "nextcloud"
cadviewer folder ：nextcloud/**custom_**apps/cadviewer

I also follow the instructions in the doc to set permissions on the right file and folder, even try 777 permission
Put `RewriteCond %{REQUEST_FILENAME} !/**custom_**apps/cadviewer/converter/php/*\.* `  in .htaccess
Change the nextcloud config in nginx
`   location /**custom_**apps/cadviewer/converter/php/ {
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            set $path_info $fastcgi_path_info;
            try_files $fastcgi_script_name =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param HTTPS on;
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;   #unix:/run/php/php8.2-fpm.sock;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
            fastcgi_max_temp_file_size 0;
        }
        try_files $uri $uri/ =403;
    }
`
In nextcloud there are some errors
`file_get_contents(/nextcloud/custom_apps/cadviewer/converter//converter/converters/ax2024/linux/ax_unmapped_fonts.txt): Failed to open stream: No such file or directory at /nextcloud/custom_apps/cadviewer/lib/Controller/SettingsController.php#275`
`file_get_contents(/nextcloud/custom_apps/cadviewer/converter//converter/converters/ax2024/linux/ax_font_map.txt): Failed to open stream: No such file or directory at /nextcloud/custom_apps/cadviewer/lib/Controller/SettingsController.php#269`

Open the dwg 
![image](https://github.com/CADViewer/NextCloud/assets/30996974/bee3b9a4-5f25-4b6b-b5cb-0fa9dd650f60)
and the nextcloud log
`Undefined array key "parameters" at /nextcloud/custom_apps/cadviewer/lib/Controller/CadviewerController.php#302`
`Undefined array key "lineWeightFactor" at /nextcloud/custom_apps/cadviewer/lib/Controller/CadviewerController.php#276`

What should I do?

**Comment by CADViewer** [comment]
Hello @bluestar800 , we just released CADViewer v8.88.5 for NextCloud which solves a similar issue in which the apps folder is named extra_apps. we believe your  custom_apps  named folder is a similar issue. Please test and let us know.

**Comment by bluestar800** [comment]
@CADViewer Thanks for your help.   I have updated the cadviewer to v8.88.5 but there still wrong. 
error still
`Undefined array key "parameters" at /nextcloud/custom_apps/cadviewer/lib/Controller/CadviewerController.php#302`
`Undefined array key "lineWeightFactor" at /nextcloud/custom_apps/cadviewer/lib/Controller/CadviewerController.php#276`
`<html>
<body>


Could not find resource cadviewer/settings/l10n/zh_CN.js to load |  
-- | --


<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by bluestar800** [comment]
@CADViewer I tried to reinstall cadviewer，but nothing changed. In doctor，the icon can not be displayed or loaded
![image](https://github.com/CADViewer/NextCloud/assets/30996974/61c52ecb-4146-48cc-94fd-314f8c38ce5e)

**Comment by CADViewer** [comment]
Hi @bluestar800 , the top screenshot of CADViewer in nextcloud, indicates that somehow the redirection of the .htaccess is not correct, as there are no icon menu being generated.    Can you please open the browser console,  Ctrl+Shift+I, and then send a listing of what CADViewer tries to load in?     It will tell us what CADViewer is trying to load in, and from the location it wants to do it from. Thanks!

**Comment by bluestar800** [comment]
/> Hi @bluestar800 , the top screenshot of CADViewer in nextcloud, indicates that somehow the redirection of the .htaccess is not correct, as there are no icon menu being generated. Can you please open the browser console, Ctrl+Shift+I, and then send a listing of what CADViewer tries to load in? It will tell us what CADViewer is trying to load in, and from the location it wants to do it from. Thanks!

This is the list：
`RESIZE - cvjs_resizeWindow_position

logoJS.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/logoJS.png 404

Image (async)

jt @ cadviewer_8.88.5.min.js:2

zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
addDrawing.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/tools/addDrawing.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
10x10.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/10x10.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
5x5.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/5x5.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
Cancel_Inactive_4.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/tools/Cancel_Inactive_4.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
Proceed_111x28_Up.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/tools/Proceed_111x28_Up.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
10x10y.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/10x10y.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
crossXy.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/crossXy.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
6x6y.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/6x6y.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
7x7.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/7x7.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
FlrPlanReorderGrip2.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/tools/FlrPlanReorderGrip2.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
blueDot.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/blueDot.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
Trash_2.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/tools/Trash_2.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
white28x10.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/white28x10.png 404
Image (async)
jt @ cadviewer_8.88.5.min.js:2
zt @ cadviewer_8.88.5.min.js:2
append @ cadviewer_8.88.5.min.js:2
hB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
blue_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/blue_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
red_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/red_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
orange_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/orange_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
yellow_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/yellow_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
green_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/green_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
purple_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/purple_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
gray_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/gray_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
brown_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/brown_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
tB @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
white_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/white_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
black_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/black_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
azure_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/azure_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
pink_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/pink_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
snow_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/snow_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
silver_color.png:1     GET https://abc.com/apps/cadviewer//assets/app//images/silver_color.png 404
Image (async)
(anonymous) @ cadviewer_8.88.5.min.js:2
W @ cadviewer_8.88.5.min.js:2
html @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
ap @ cadviewer_8.88.5.min.js:2
lp @ cadviewer_8.88.5.min.js:2
(anonymous) @ cadviewer_8.88.5.min.js:2
xh @ cadviewer_8.88.5.min.js:2
initCadviewer @ CADViewerCanvas.vue:773
(anonymous) @ CADViewerCanvas.vue:14
d @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
(anonymous) @ CADViewerCanvas.vue:42
y @ CADViewerCanvas.vue:228
r @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:237
(anonymous) @ CADViewerCanvas.vue:234
(anonymous) @ CADViewerCanvas.vue:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
S @ jquery.js:9878
(anonymous) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonymous) @ jquery-migrate.min.js:2
t.<computed> @ jquery-migrate.min.js:2
viewCadFileActionHandler @ CADViewerCanvas.vue:1001
action @ merged-index.js?v=ad91e066-18:3086
_onClickFile @ merged-index.js?v=ad91e066-18:5085
Bt @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
dispatch @ jquery.js:5466
f.handle @ jquery.js:5270
looper.gif:1     GET https://abc.com/apps/cadviewer//assets/app//images/looper.gif 404`

**Comment by bluestar800** [comment]
There is some error in browser console，like this：
XHRPOST https://abc.com/apps/cadviewer/converter/php/call-Api_Conversion.php [HTTP/2 404  116ms]
GET https://abc.com/apps/cadviewer//assets/app//images/cvjsToolbar_dra_pageChange_11B.png [HTTP/2 404  115ms]
Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times 
XHRPOST https://abc.com/apps/cadviewer/converter/php/load-file.php [HTTP/2 404  65ms]
Content-Security-Policy：页面设置阻止读取位于 eval 的一项资源("script-src")。 2 cadviewer_9.17.2.min.js:2:1558

**Comment by CADViewer** [comment]
Hello @bluestar800 , so we have one fix up which is when using Snap with Nextcloud on Ubuntu 22.04, the apps are installed into ***extra-apps***, so we have a fix for that , it should also work for ***custom-apps** but we have not been able to verify on a platform that uses ***custom-apps***, so please check.

**Comment by bluestar800** [comment]
> Hello @bluestar800 , so we have one fix up which is when using Snap with Nextcloud on Ubuntu 22.04, the apps are installed into _**extra-apps**_, so we have a fix for that , it should also work for ***custom-apps** but we have not been able to verify on a platform that uses _**custom-apps**_, so please check.

I got it and updated to 9.18.8  but the issues persist. The issues just like this :
> There is some error in browser console，like this： XHRPOST https://abc.com/apps/cadviewer/converter/php/call-Api_Conversion.php [HTTP/2 404 116ms] GET https://abc.com/apps/cadviewer//assets/app//images/cvjsToolbar_dra_pageChange_11B.png [HTTP/2 404 115ms] Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times XHRPOST https://abc.com/apps/cadviewer/converter/php/load-file.php [HTTP/2 404 65ms] Content-Security-Policy：页面设置阻止读取位于 eval 的一项资源("script-src")。 2 cadviewer_9.17.2.min.js:2:1558

The url is incorrect  https://abc.com/apps/cadviewer//assets/app//images/cvjsToolbar_dra_pageChange_11B.png
It maybe: https://abc.com/apps/cadviewer/assets/app/images/cvjsToolbar_dra_pageChange_11B.png

Nextcloud on debian 11 by php8.2 nginx and mariadb

**Comment by bluestar800** [comment]
When I continue to install V9.19.6 in the custom_apps folder, the browser console shows that the called cadviewer is still in the apps folder.
I tried installing to apps folder ， but I still get the error.  （The customs_apps folder still exists and is used by others）(`RewriteCond %{REQUEST_FILENAME} !/**custom_apps**/cadviewer/converter/php/*\.*`  changed to `RewriteCond %{REQUEST_FILENAME} !/**apps**/cadviewer/converter/php/*\.*` )
The console shows ： 
`cadviewer_9.19.6.min.js:2  POST https://abc.com/apps/cadviewer/converter/php/call-Api_Conversion.php 404`

`cadviewer_9.19.6.min.js:2  POST https://abc.com/apps/cadviewer/converter/php/load-file.php 404`

`focus-trap.esm.js:482 Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at h (focus-trap.esm.js:482:15)
    at Object.activate (index.js:45:15)
    at NcModal.js:2:170598
    at d (NcModal.js:2:159742)
    at Generator.<anonymous> (NcModal.js:2:161079)
    at Generator.next (NcModal.js:2:160105)
    at A (NcModal.js:2:165730)
    at r (NcModal.js:2:170752)
`
In nextcloud logs：
`Undefined array key "parameters" at /var/www/nextcloud/apps/cadviewer/lib/Controller/CadviewerController.php#302`
`Undefined array key "lineWeightFactor" at /var/www/nextcloud/apps/cadviewer/lib/Controller/CadviewerController.php#276`


What should I do？

**Comment by CADViewer** [comment]
Hello @bluestar800 , with the latest version 9.47.1, we have added code to check the .httacess and update the rewrite conditions, and if there is insufficient permissions, we now provide an error message in the admin console with instructions.
